language: node_js
sudo: false
node_js: 
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - ./dist
install:
  - npm ci
stages:
  - name: build
  - name: check-cache
jobs:
  include:
    - stage: build
      script: npm run build && ls -lha
    - stage: check-cache
      script: ls -lha && ls -lha ./dist
